export type Pdf = (typeof mockPdfs)[0];

export const mockPdfs = [
    {
        id: 1,
        fileName: "test1.pdf",
        clientNumber: "CN001",
        installationNumber: "IN001",
        vencimento: "2023-05-01",
        data: "2023-04-01",
        valorAPagar: "100.00",
        notaFiscal: "NF001",
        serie: "S001",
        dataEmissao: "2023-04-01",
        codigoDeBarras: "1234567890",
        icmsTotal: "10.00",
        pasepTotal: "5.00",
        cofinsTotal: "5.00",
        nomeCliente: "John Doe",
        distribuidora: "Energy Co.",
        valoresFaturados: null,
        energiaCompensada: null,
    },
    {
        id: 2,
        fileName: "test2.pdf",
        clientNumber: "CN002",
        installationNumber: "IN002",
        vencimento: "2023-05-02",
        data: "2023-04-02",
        valorAPagar: "200.00",
        notaFiscal: "NF002",
        serie: "S002",
        dataEmissao: "2023-04-02",
        codigoDeBarras: "0987654321",
        icmsTotal: "20.00",
        pasepTotal: "10.00",
        cofinsTotal: "10.00",
        nomeCliente: "Jane Doe",
        distribuidora: "Power Inc.",
        valoresFaturados: null,
        energiaCompensada: null,
    },
];

export type PdfValues = typeof mockClientDataValues;

export const mockClientDataValues = {
    id: 3,
    fileName: "newFile.pdf",
    clientNumber: "CN003",
    installationNumber: "IN003",
    vencimento: "2023-05-03",
    data: "2023-04-03",
    valorAPagar: "300.00",
    notaFiscal: "NF003",
    serie: "S003",
    dataEmissao: "2023-04-03",
    codigoDeBarras: "1122334455",
    icmsTotal: "30.00",
    pasepTotal: "15.00",
    cofinsTotal: "15.00",
    nomeCliente: "Bob Smith",
    distribuidora: "Electric LLC",
    valoresFaturados: [
        {
            tipo: "Energia",
            quantidade: 100,
            precoUnit: 3,
            valorTotal: "300.00",
            pisCofins: "30.00",
            icms: "30.00",
            tarifaUnit: "3",
        },
    ],
    energiaCompensada: {
        unidade: "kWh",
        quantidade: "50",
        precoUnit: "2",
        valorTotal: "100.00",
        pisCofins: "10.00",
        icms: "10.00",
        tarifaUnit: "2",
    },
    contribuicaoIlumPublica: {
        unidade: "R$",
        quantidade: "1",
        valorTotal: "10.00",
    },
    total: {
        unidade: "R$",
        quantidade: "1",
        valorTotal: "310.00",
    },
    bandeiraVermelha: {
        unidade: "R$",
        quantidade: "1",
        valorTotal: "5.00",
    },
};
